### ISSUE TITLE
Оптимизировать алгоритм

### ISSUE THREAD

**Issue by ulitcos** [Promo/wheel-indicator#21]
Надо попробовать уменьшить кол-во проверяемых значение дельты с 5 до 3-х

**Comment by f0rmat1k** [comment]
@ulitcos еще есть баг "вверх-вниз"

**Comment by ulitcos** [comment]
"Вверх-вниз" поправил.

**Comment by f0rmat1k** [comment]
Закрываем?

**Comment by ulitcos** [comment]
Не знаю, может кто лучше предложит?

**Comment by f0rmat1k** [comment]
@ulitcos ну как предложит, так и создаст ишью, не?
