### ISSUE TITLE
Поддержка IE10+?

### ISSUE THREAD

**Issue by kuflash** [Promo/wheel-indicator#33]
Добрый день! Не могу понять есть ли поддержка IE10+, но callback не срабатывает в этих браузерах..

**Comment by f0rmat1k** [comment]
@kuflash Привет. У меня в ИЕ10 все работает. На демо-странице http://promo.github.io/wheel-indicator/

**Comment by kuflash** [comment]
Прошу прощения) Действительно в проекте просто блочился event)

**Comment by f0rmat1k** [comment]
Эх, никто никогда ишью за собой не закрывает..
