### ISSUE TITLE
require.js compatibility

### ISSUE THREAD

**Issue by riccardolardi** [Promo/wheel-indicator#41]
How to get this to work with require.js?

**Comment by f0rmat1k** [comment]
@alberto2000 just `require('wheel-indicator')` not working?
We [do export](https://github.com/Promo/wheel-indicator/blob/master/lib/wheel-indicator.js#L241) of constructor.

**Comment by riccardolardi** [comment]
@f0rmat1k Sorry - my bad. It works like expected. Thanks! Issue obsolete!
