### ISSUE TITLE
deltaY value of -0 (minus zero)

### ISSUE THREAD

**Issue by riccardolardi** [Promo/wheel-indicator#42]
On OS X El Capitan using Chrome 47.0.2526.73 (64-bit)

I sometimes get a value of -0 (minus zero) when scrolling, which is interpreted as direction "up". It is annoying because it also happens while scrolling downwards. Any hint on this?

**Comment by f0rmat1k** [comment]
@alberto2000 Hello. I couldn't repeat this case. Can you repeat it on [demo stand](http://promo.github.io/wheel-indicator/) (section "Hover, wheel and see deltaY") and paste here the sequence?

**Comment by f0rmat1k** [comment]
@alberto2000 we confirmed the problem and fixed it. Check please version 1.1.2.

**Comment by riccardolardi** [comment]
Hi Anton

Thanks, it looks like it’s fixed with 1.1.3

Best,
Riccardo

–––
Riccardo Lardi
MA Design Interactions, Royal College of Art, London
hello@riccardolardi.com
+44 7402 642331

On 10 December 2015 at 09:09:10, Anton Grischenko (notifications@github.com) wrote:

Closed #42.
