### ISSUE TITLE
Provide minified  jsLinted CDN version

### ISSUE THREAD

**Issue by englishextra** [Promo/wheel-indicator#49]
This is what I've found so far:

```
//cdn.jsdelivr.net/npm/wheel-indicator@1.1.4/lib/wheel-indicator.js
```
The other suggestion is to fix jsLint warning: see here https://github.com/Promo/wheel-indicator/issues/29#issuecomment-329980171

**Comment by MartinKolarik** [comment]
You could also use https://cdn.jsdelivr.net/npm/wheel-indicator@1.1.4/lib/wheel-indicator.min.js

**Comment by englishextra** [comment]
@MartinKolarik      Thanks
