### ISSUE TITLE
Support passive listener

### ISSUE THREAD

**Issue by englishextra** [Promo/wheel-indicator#50]
```
    function addEvent(elem, type, handler){
        if(elem.addEventListener) {
            elem.addEventListener(type, handler, false);
        } else if (elem.attachEvent) {
            elem.attachEvent('on' + type, handler);
        }
    }
```

Please see here: 
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection

The workaround for Lighthouse report is to test for passive support
```
var supportsPassive = false;
try {
	var opts = Object.defineProperty({}, "passive", {
			get: function () {
				supportsPassive = true;
			}
		});
	root.addEventListener("test", null, opts);
} catch (e) {}
```
If fails, include polyfill
```
	if (!supportsPassive) {
		scriptsArray.push("//cdnjs.cloudflare.com/ajax/libs/dom4/1.8.3/dom4.js");
	}
```
and change in wheel-indicator.js
```
    function addEvent(elem, type, handler){
        if(elem.addEventListener) {
            elem.addEventListener(type, handler, {passive: true});
        } else if (elem.attachEvent) {
            elem.attachEvent('on' + type, handler);
        }
    }

    function removeEvent(elem, type, handler) {
        if (elem.removeEventListener) {
            elem.removeEventListener(type, handler, {passive: true});
        } else if (elem.detachEvent) {
            elem.detachEvent('on'+ type, handler);
        }
    }
```
In that case the Lighthouse addon for Chrome is happy.

I suspect in other use cases the solution above may not be acceptable.

**Comment by harmvandeven** [comment]
In the latest version of OsX Chrome (Version 73.0.3683.86 (Official Build) (64-bit)) this now leads to console errors. Is somebody looking in to this?

> [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
> preventDefault @ wheel-indicator.js:103
> Module._wheelHandler @ wheel-indicator.js:33

**Comment by englishextra** [comment]
@harmvandeven I use 67.0.3396.87 (Official Build) (64-bit) So I continue with the solution above, and can't offer any suggestion.

**Comment by ondrejrohon** [comment]
This PR should fix it, let me know if you have any troubles!

**Comment by englishextra** [comment]
thanks

**Comment by f0rmat1k** [comment]
added with wheel-indicator@1.2.2
