### ISSUE TITLE
React State Undefind in callback Function

### ISSUE THREAD

**Issue by Osamasomy** [Promo/wheel-indicator#54]
can not read state in call back function althogh i am binding callback but its not work.

**Comment by Osamasomy** [comment]
![image](https://user-images.githubusercontent.com/29625742/47237391-54a13000-d3f8-11e8-8aab-26c0e0bba0ed.png)


error is " abc can not read on undefined"

**Comment by f0rmat1k** [comment]
fixed in v1.2.1
